# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/bruno/Documents/Engine/C++/Linux_Unreal_Engine_5.4.4
GAMEPROJECTFILE =/home/bruno/Documents/Unreal Projects/ICantCry/ICantCry.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	ICantCry-Linux-DebugGame  \
	ICantCry-Linux-Shipping  \
	ICantCry \
	ICantCryEditor-Linux-DebugGame  \
	ICantCryEditor-Linux-Shipping  \
	ICantCryEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ICantCryEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ICantCryEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

ICantCry-Linux-DebugGame:
	 $(PROJECTBUILD) ICantCry Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ICantCry-Linux-Shipping:
	 $(PROJECTBUILD) ICantCry Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ICantCry:
	 $(PROJECTBUILD) ICantCry Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ICantCryEditor-Linux-DebugGame:
	 $(PROJECTBUILD) ICantCryEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ICantCryEditor-Linux-Shipping:
	 $(PROJECTBUILD) ICantCryEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ICantCryEditor:
	 $(PROJECTBUILD) ICantCryEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
